language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- pypy3.5
before_install:
- sudo apt-get update
install:
- wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.10/jellyfish-2.2.10.tar.gz
- tar zxf jellyfish-2.2.10.tar.gz
- pushd jellyfish-2.2.10 && \
      ./configure --enable-python-binding && \
      make && \
      sudo make install && \
      popd
- export PKG_CONFIG_PATH=$HOME/jellyfish-2.2.10 && \
      pushd $HOME/jellyfish-2.2.10/swig/python && \
      python setup.py build && \
      python setup.py install && \
      popd
- python -m pip install -r requirements.txt
script:
- "./unit_test.sh"
- "./test/sm.sh python"
notifications:
  slack:
    secure: AZuRMFO1v16OhVdziC/BggoCyjTpe4ErcS4i5eHXhKh72RUC2tCdPIUNCnDybpKhmSrKXwPrMe0QoEUcuQYk/ftmI+Jyp1ttqaKizkNNAe1LJW4SVZQqpFpqUEPYqaPDxEoQrKTqJNsAE+pMrvnPnkmYHiiFHS8eGuSSgYVR/OdjeXiFL0C+hJMxwFTAbdWaakKVq1NOGXRP33HPRTDO7jGO83IiU0X8HoCNSQpIXV18TqgYv6V21OPhWMcGi4NnVVU+hF58IgTcDyXMHttndw4hIlrKrDD7BkBywVhkrcYn0UxgVXgsLBz0RTsOf70X3D/lOjn9GNFYI07Xgpj4MXOmWo2rPdQiVtGjs4TlHR6+dkTlS7IyM9eicAkqSC4P4CFZfMRDmcwaiGeXKtofuqYDSxJfuKxBP5i/spMyilI0VuCWyJJxTQBe7WWKeMNgtN60je6XQE6+J5SffIFPFdRzy+rMCSgiRal1Zxmar0ixgOufch7dUAJAHORrWrE2cj+m1afDt/3Osm4dC3SvPTttJ4Mk3iEDpI0V9KC7fapFSA9BS/Zj6WXrv6KLQzjsrkHrWRAu1ynrbSM/WKd3a+ValgTw+GzmkDkIPH9S+ZXIToPKglR+ie5JO/F7bVxsiJlUntZmRwDHX8jD7iaDEXNaNFYAf3zidFa7OJ7Nk9M=
