language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
# PyPy versions
- "pypy2.7"
- "pypy3.5"
before_install:
- sudo apt-get update
- sudo apt-get install -y liblzo2-dev
install:
- pip install --upgrade pip setuptools
- pip install -r requirements.txt
script:
- "./unit_test.sh"
notifications:
  slack:
    secure: acBJ7SM1nqyrPqHB5y0AzoqBUERrEplP7on3s3BkNmhGkfU435qfQTlx/n9xFeY70/kgQhUii6ta1JEsxMK+sb2DgpOTI7Q7rAu34YEQFS5PH/kIBl6O8BD8SPomRXkMIM5NRT2yavoc363joxUKkYqJAlLu0ZDacsOF0TGTFrL9kJcnRJf+u5XJRKlw6YOPIqyoKJYZVhFDS30uq/og4H9lFUwhgn8wXoIU5vKq1Wn78U0OdrtHnKkRQPt2Ve7UKeiWyT6vIw1JyHaVBiBcn5bVvyXyiQNRnUtxhgqmESPvT4TkUO7IEatfQ1oqS4B0xvBMlf8KBWmvpnlitGuRB68fZIy1YVR9OYFt0/hoTTSW9sHQ+gRj5m5t/R+ppV+L//u0T/cm3hJh4Zs2J2tvn3/j107x15AFhbXp6ItzRDzHDSzQHmsYz2mdhxTQJPym3jIq89zlSsA5NHnQQGrOJeAbztnwIHff8HVEiSErpDCZpIo6+HJphnH0cM3ugWrDR6qIkyvg5fvDFgGh/2vYCNCloniugCjknJp58eeLFytOZ7a9Rz3FhKGTKmjN0NAM4dEr5sNkhE2i1i6JizB4qt+JM72n7lZcdFEGaLSWAtVdt2W1pNwomx9zI4OkgFzp3HA2lOKWXVoF0QKYeXwAPG8ytzCDvNXlf20utPQ2FLk=
